services:
  main:
    container_name: main
    image: us-central1-docker.pkg.dev/${GCP_PROJECT_ID}/core-backend/live:latest
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - mysql
      - mongodb
      - redis
    volumes:
      - ./.env:/app/.env
