version: '3'

services:
  main:
    container_name: main
    image: ccsiew/game-core:latest
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - mysql
      - mongodb
    volumes:
      - ./.env:/app/.env
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    networks:
      - webnet
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - webnet
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./backup:/data/backup
  webserver:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - main
    networks:
      - webnet
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - webnet
networks:
  webnet:
    driver: bridge
volumes:
  mysql_data:
  mongo_data:
