services:
  main:
    container_name: main
    image: us-central1-docker.pkg.dev/${GCP_PROJECT_ID}/core-backend/live:latest
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
      - ./server-ca.pem:/app/server-ca.pem
    networks:
      - external_network
networks:
  external_network:
    external: true
