/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DepositInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "deposit"
      | "depositAdmin"
      | "distributeReferralFee"
      | "gameUSDPool"
      | "initialize"
      | "owner"
      | "payoutPool"
      | "proxiableUUID"
      | "renounceOwnership"
      | "revokeExpiredCredit"
      | "setDepositAdmin"
      | "setGameUSDPoolContract"
      | "setPayoutPoolContract"
      | "transferOwnership"
      | "upgradeToAndCall"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposit"
      | "DepositAdminSet"
      | "ExpiredCreditRevoked"
      | "GameUSDPoolContractSet"
      | "Initialized"
      | "OwnershipTransferred"
      | "PayoutPoolContractSet"
      | "ReferralFeeDistributed"
      | "Upgraded"
      | "Withdraw"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "distributeReferralFee",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gameUSDPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payoutPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeExpiredCredit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDepositAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setGameUSDPoolContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPayoutPoolContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeReferralFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gameUSDPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payoutPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeExpiredCredit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDepositAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGameUSDPoolContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPayoutPoolContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace DepositEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositAdminSetEvent {
  export type InputTuple = [depositBot: AddressLike];
  export type OutputTuple = [depositBot: string];
  export interface OutputObject {
    depositBot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExpiredCreditRevokedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameUSDPoolContractSetEvent {
  export type InputTuple = [gameUSDPool: AddressLike];
  export type OutputTuple = [gameUSDPool: string];
  export interface OutputObject {
    gameUSDPool: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayoutPoolContractSetEvent {
  export type InputTuple = [payoutPool: AddressLike];
  export type OutputTuple = [payoutPool: string];
  export interface OutputObject {
    payoutPool: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralFeeDistributedEvent {
  export type InputTuple = [referrer: AddressLike, referralFee: BigNumberish];
  export type OutputTuple = [referrer: string, referralFee: bigint];
  export interface OutputObject {
    referrer: string;
    referralFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    amountAfterFees: BigNumberish,
    payoutNonce: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    amountAfterFees: bigint,
    payoutNonce: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    amountAfterFees: bigint;
    payoutNonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Deposit extends BaseContract {
  connect(runner?: ContractRunner | null): Deposit;
  waitForDeployment(): Promise<this>;

  interface: DepositInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  deposit: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  depositAdmin: TypedContractMethod<[], [string], "view">;

  distributeReferralFee: TypedContractMethod<
    [referrer: AddressLike, referralFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  gameUSDPool: TypedContractMethod<[], [string], "view">;

  initialize: TypedContractMethod<
    [owner: AddressLike, _depositAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  payoutPool: TypedContractMethod<[], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeExpiredCredit: TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDepositAdmin: TypedContractMethod<
    [_depositAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  setGameUSDPoolContract: TypedContractMethod<
    [_gameUSDPool: AddressLike],
    [void],
    "nonpayable"
  >;

  setPayoutPoolContract: TypedContractMethod<
    [_payoutPool: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  withdraw: TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish, fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "distributeReferralFee"
  ): TypedContractMethod<
    [referrer: AddressLike, referralFee: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gameUSDPool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [owner: AddressLike, _depositAdmin: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payoutPool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeExpiredCredit"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDepositAdmin"
  ): TypedContractMethod<[_depositAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGameUSDPoolContract"
  ): TypedContractMethod<[_gameUSDPool: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPayoutPoolContract"
  ): TypedContractMethod<[_payoutPool: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish, fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "DepositAdminSet"
  ): TypedContractEvent<
    DepositAdminSetEvent.InputTuple,
    DepositAdminSetEvent.OutputTuple,
    DepositAdminSetEvent.OutputObject
  >;
  getEvent(
    key: "ExpiredCreditRevoked"
  ): TypedContractEvent<
    ExpiredCreditRevokedEvent.InputTuple,
    ExpiredCreditRevokedEvent.OutputTuple,
    ExpiredCreditRevokedEvent.OutputObject
  >;
  getEvent(
    key: "GameUSDPoolContractSet"
  ): TypedContractEvent<
    GameUSDPoolContractSetEvent.InputTuple,
    GameUSDPoolContractSetEvent.OutputTuple,
    GameUSDPoolContractSetEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PayoutPoolContractSet"
  ): TypedContractEvent<
    PayoutPoolContractSetEvent.InputTuple,
    PayoutPoolContractSetEvent.OutputTuple,
    PayoutPoolContractSetEvent.OutputObject
  >;
  getEvent(
    key: "ReferralFeeDistributed"
  ): TypedContractEvent<
    ReferralFeeDistributedEvent.InputTuple,
    ReferralFeeDistributedEvent.OutputTuple,
    ReferralFeeDistributedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;
  getEvent(
    key: "Withdraw"
  ): TypedContractEvent<
    WithdrawEvent.InputTuple,
    WithdrawEvent.OutputTuple,
    WithdrawEvent.OutputObject
  >;

  filters: {
    "Deposit(address,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "DepositAdminSet(address)": TypedContractEvent<
      DepositAdminSetEvent.InputTuple,
      DepositAdminSetEvent.OutputTuple,
      DepositAdminSetEvent.OutputObject
    >;
    DepositAdminSet: TypedContractEvent<
      DepositAdminSetEvent.InputTuple,
      DepositAdminSetEvent.OutputTuple,
      DepositAdminSetEvent.OutputObject
    >;

    "ExpiredCreditRevoked(address,uint256)": TypedContractEvent<
      ExpiredCreditRevokedEvent.InputTuple,
      ExpiredCreditRevokedEvent.OutputTuple,
      ExpiredCreditRevokedEvent.OutputObject
    >;
    ExpiredCreditRevoked: TypedContractEvent<
      ExpiredCreditRevokedEvent.InputTuple,
      ExpiredCreditRevokedEvent.OutputTuple,
      ExpiredCreditRevokedEvent.OutputObject
    >;

    "GameUSDPoolContractSet(address)": TypedContractEvent<
      GameUSDPoolContractSetEvent.InputTuple,
      GameUSDPoolContractSetEvent.OutputTuple,
      GameUSDPoolContractSetEvent.OutputObject
    >;
    GameUSDPoolContractSet: TypedContractEvent<
      GameUSDPoolContractSetEvent.InputTuple,
      GameUSDPoolContractSetEvent.OutputTuple,
      GameUSDPoolContractSetEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PayoutPoolContractSet(address)": TypedContractEvent<
      PayoutPoolContractSetEvent.InputTuple,
      PayoutPoolContractSetEvent.OutputTuple,
      PayoutPoolContractSetEvent.OutputObject
    >;
    PayoutPoolContractSet: TypedContractEvent<
      PayoutPoolContractSetEvent.InputTuple,
      PayoutPoolContractSetEvent.OutputTuple,
      PayoutPoolContractSetEvent.OutputObject
    >;

    "ReferralFeeDistributed(address,uint256)": TypedContractEvent<
      ReferralFeeDistributedEvent.InputTuple,
      ReferralFeeDistributedEvent.OutputTuple,
      ReferralFeeDistributedEvent.OutputObject
    >;
    ReferralFeeDistributed: TypedContractEvent<
      ReferralFeeDistributedEvent.InputTuple,
      ReferralFeeDistributedEvent.OutputTuple,
      ReferralFeeDistributedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;

    "Withdraw(address,uint256,uint256,uint256)": TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
    Withdraw: TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
  };
}
