/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface JackpotHashInterface extends Interface {
  getFunction(
    nameOrSignature: "emitJackpotHash" | "jackpotHashes"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "JackpotHashEmitted"): EventFragment;

  encodeFunctionData(
    functionFragment: "emitJackpotHash",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "jackpotHashes",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "emitJackpotHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "jackpotHashes",
    data: BytesLike
  ): Result;
}

export namespace JackpotHashEmittedEvent {
  export type InputTuple = [
    uid: BigNumberish,
    ticketId: BigNumberish,
    hash: BytesLike
  ];
  export type OutputTuple = [uid: bigint, ticketId: bigint, hash: string];
  export interface OutputObject {
    uid: bigint;
    ticketId: bigint;
    hash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface JackpotHash extends BaseContract {
  connect(runner?: ContractRunner | null): JackpotHash;
  waitForDeployment(): Promise<this>;

  interface: JackpotHashInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  emitJackpotHash: TypedContractMethod<
    [uid: BigNumberish, ticketId: BigNumberish, hash: BytesLike],
    [void],
    "nonpayable"
  >;

  jackpotHashes: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "emitJackpotHash"
  ): TypedContractMethod<
    [uid: BigNumberish, ticketId: BigNumberish, hash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "jackpotHashes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  getEvent(
    key: "JackpotHashEmitted"
  ): TypedContractEvent<
    JackpotHashEmittedEvent.InputTuple,
    JackpotHashEmittedEvent.OutputTuple,
    JackpotHashEmittedEvent.OutputObject
  >;

  filters: {
    "JackpotHashEmitted(uint256,uint256,bytes32)": TypedContractEvent<
      JackpotHashEmittedEvent.InputTuple,
      JackpotHashEmittedEvent.OutputTuple,
      JackpotHashEmittedEvent.OutputObject
    >;
    JackpotHashEmitted: TypedContractEvent<
      JackpotHashEmittedEvent.InputTuple,
      JackpotHashEmittedEvent.OutputTuple,
      JackpotHashEmittedEvent.OutputObject
    >;
  };
}
