export enum QueueName {
  BET = 'BET_QUEUE',
  GAME = 'GAME_QUEUE',
  CREDIT = 'CREDIT_QUEUE',
  WITHDRAW = 'WITHDRAW_QUEUE',
}

export enum QueueType {
  SUBMIT_BET = 'SUBMIT_BET',
  SUBMIT_SUCCESS_PROCESS = 'SUBMIT_SUCCESS_PROCESS',
  SUBMIT_DRAW_RESULT = 'SUBMIT_DRAW_RESULT',
  SUBMIT_CREDIT = 'SUBMIT_CREDIT',
  PROCESS_WITHDRAW = 'PROCESS_WITHDRAW',
  PROCESS_PAYOUT = 'PROCESS_PAYOUT',
}
