export enum WalletTxType {
  DEPOSIT = 'DEPOSIT',
  PLAY = 'PLAY',
  CLAIM = 'CLAIM',
  REDEEM = 'REDEEM',
  REFERRAL = 'REFERRAL',
  INTERNAL_TRANSFER = 'INTERNAL_TRANSFER',
  CAMPAIGN = 'CAMPAIGN',
  GAME_TRANSACTION = 'GAME_TRANSACTION',
  CLAIM_JACKPOT = 'CLAIM_JACKPOT',
}

export enum ReferralTxType {
  DEPOSIT = 'DEPOSIT',
  PRIZE = 'PRIZE',
  BET = 'BET',
  SET_REFERRAL = 'SET_REFERRAL',
}

export enum CreditWalletTxType {
  CREDIT = 'CREDIT',
  PLAY = 'PLAY',
  CAMPAIGN = 'CAMPAIGN',
  GAME_TRANSACTION = 'GAME_TRANSACTION',
  EXPIRY = 'EXPIRY',
}

export enum PointTxType {
  GAME_TRANSACTION = 'GAME_TRANSACTION',
  CLAIM = 'CLAIM',
  CAMPAIGN = 'CAMPAIGN',
  DEPOSIT = 'DEPOSIT',
  BET = 'BET',
  CHAT = 'CHAT',
  REFERRAL = 'REFERRAL',
  QUEST = 'QUEST',
  ADJUSTMENT = 'ADJUSTMENT',
}

export enum UsdtTxType {
  GAME_TRANSACTION = 'GAME_TRANSACTION',
  CAMPAIGN = 'CAMPAIGN',
}