insert into permission (code, description, roles) values ('get_permission_access', 'Get Permission Access', 'S,F,M,O,R');
insert into permission (code, description, roles) values ('get_permission', 'Get Permission', 'S,F,M,O,R');
insert into permission (code, description, roles) values ('get_audit_log', 'Get Audit Log', 'S,F,M');
insert into permission (code, description, roles) values ('reset_admin_password', 'Reset Admin Password', 'S,F,M,O');
insert into permission (code, description, roles) values ('get_admin', 'Get Admin', 'S,F,M,O,R');
insert into permission (code, description, roles) values ('get_setting', 'Get Setting', 'S,F,M,O');
insert into permission (code, description, roles) values ('manage_wallet', 'Manage User Wallet', 'S');
insert into permission (code, description, roles) values ('update_user_status', 'Update user status', 'S');
insert into permission (code, description, roles) values ('supply_game_usd', 'Supply GameUSD', 'S, B');
insert into permission (code, description, roles) values ('set_bet_close', 'Set bet close', 'S, B');
insert into permission (code, description, roles) values ('fetch_draw_result', 'Fetch draw result', 'S, B');
insert into permission (code, description, roles) values ('submit_last_minute_draw', 'Submit last minute draw', 'S, B');
insert into permission (code, description, roles) values ('update_payout_signature', 'Update payout signature', 'S, B');
insert into permission (code, description, roles) values ('payout', 'Payout USDT', 'S, B');